### ISSUE TITLE
Question: how do I include images?

### ISSUE THREAD

**Issue by johannesE** [matgargano/vue-wordpress-plugin#4] opened 2017-12-11 16:48 UTC
I want to use images in my vue plugin. I should probably add something to the webpack config. Any ideas? I'm asking this here because I'm pretty sure this repo could benefit from a solution.

**Comment by matgargano** [comment] 2018-01-10 16:06
Let me know if you come up with anything -- and feel free to fork @johannesE  since this is not a bug per-se let's see if anyone wants to help here.

**Comment by johannesE** [comment] 2018-01-10 16:09
For now I upload the images to wordpress and include them with their path 🙄. Not the best solution, I know..

**Comment by matgargano** [comment] 2018-05-09 16:06
I'm going to close this, please reopen if you need to

**Closed as completed by matgargano** 2018-05-09 16:06 UTC
Labels: enhancement, help wanted
