### ISSUE TITLE
I have a question.

### ISSUE THREAD

**Issue by idpokute** [matgargano/vue-wordpress-plugin#2] opened 2017-07-31 03:35 UTC
Hello.
First of all, good job @matgargano 
I concern an issue.What if I make 2 plugins using this starter?
I guess those two plugins load the same common files such as vue-core, vue-router and etc.
Some files, vue-core and etc, should be loaded by php side such as enqueue script. Then those two plugins can handle the common file.

**Comment by matgargano** [comment] 2017-08-31 00:58
@idpokute  can you give me an example of what you are trying to accomplish -- and what you've tried

**Comment by idpokute** [comment] 2017-08-31 18:10
Maybe my example is not enough with detail. I will give simpler example. l make 2 plugins using this starter, let's call myWidget and myList. When you active them. WP site load vue-core twice, right? That's my point. If the plugin supports some kinda options to prevent loading same dependencies, it will be great.

**Comment by matgargano** [comment] 2017-08-31 18:29
@idpokute go ahead and make a pull request for that! i would love to get contributions from the community for this

**Comment by johannesE** [comment] 2017-12-04 20:42
I am not really a professional on this, but I think there are 2 factors preventing this from loading twice:
- your browser does not load the same resource twice
- The vue.js file should be included in this plugin with some wordpress enqueue function. This also prevents double loading of the same resource.

**Comment by matgargano** [comment] 2017-12-04 21:10
I gotcha. The problem is -- there is no central VueJS within WordPress - if
it enqueues with a handle of `vue-js` and someone else enqueues it as
`vuejs` we will end up with a duplicate anyway and an extra roundtrip to the server which would negatively impact users if you are using HTTP 1.1.

Either way feel free to split it in webpack and issue a PR and I'll take a
look.

**Comment by matgargano** [comment] 2017-12-05 14:50
closing this out

**Closed as completed by matgargano** 2017-12-05 14:50 UTC
Labels: help wanted, question
